#!/bin/bash

echo "🚀 部署Admin V3到Vercel..."
echo ""
echo "修复内容："
echo "- 将Edge Function从本地验证改为代理模式"
echo "- 直接转发请求到Railway后端"
echo "- 支持正确的管理员凭据验证"
echo ""
echo "请手动执行以下命令："
echo ""
echo "1. 在Windows PowerShell或Git Bash中运行："
echo "   cd /mnt/c/Users/david/Desktop/ai-pm-admin-v3-standalone"
echo "   git push origin main"
echo ""
echo "2. Vercel会自动部署，等待约1-2分钟"
echo ""
echo "3. 访问 https://ai-pm-admin-v3-prod.vercel.app 测试登录"
echo "   用户名: davidwang812"
echo "   密码: @13910008788!"
echo ""
echo "✅ 修复已本地提交，请手动推送到GitHub"